name: Cache Prime Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Cache dependencies
      - name: prime-cache-054eabb
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-054eabb

      # ✅ Report whether cache was hit or missed
      - name: Show cache result
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
