name: Email Action Test

on:
  push:
  workflow_dispatch:  # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 22f3001255@ds.study.iitm.ac.in
        run: echo "Hello, world from GitHub Actions!"
